sudo: required
services:
  - docker
language: node_js
node_js:
  - "iojs"
  - "10.15"
before_install:
  - docker build -t anilkmr458/react-docker -f Dockerfile.dev . 

script:
  - docker run anilkmr458/react-docker -- --coverage