sudo: required
services:
  - docker
language: node_js
node_js:
  - "iojs"
  - "10.15"
before_install:
  - docker build -t anilkmr458/react-docker -f Dockerfile.dev . 

script:
  - docker run anilkmr458/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "react-docker"
  env: "React-docker-env"
  bucket_name: "elasticbeanstalk-us-west-2"
  bucket_path: "react-docker"
  on:
    branch: master
